from enum import IntEnum, Enum


class HttpStatus(IntEnum):
    OK = 200
    CREATED = 201
    NO_CONTENT = 204
    BAD_REQUEST = 400
    UNAUTHORIZED = 401
    FORBIDDEN = 403
    NOT_FOUND = 404
    METHOD_NOT_ALLOWED = 405
    CONFLICT = 409
    INTERNAL_SERVER_ERROR = 500


class ErrorCode(str, Enum):
    """Centralized error codes for API responses."""
    USER_ID_REQUIRED = "USER_ID_REQUIRED"
    FORBIDDEN = "FORBIDDEN"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    ITEM_ALREADY_EXISTS = "ITEM_ALREADY_EXISTS"
    ITEM_NOT_FOUND = "ITEM_NOT_FOUND"
    EMPTY_REQUEST_BODY = "EMPTY_REQUEST_BODY"
    INVALID_JSON = "INVALID_JSON"
    CONCURRENT_MODIFICATION = "CONCURRENT_MODIFICATION"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
